#!/bin/bash
source ~/.xprofile

xrandr --output HDMI-0 --right-of DP-0
xrandr --output DP-0 --primary

# Some programs
mpd &
dunst &

hsetroot -fill ~/.wallpaper
unclutter -b --timeout 3 &
nm-applet &

dropbox-cli start &

# Sets default cursor to be a left ptr and not an X
xsetroot -cursor_name left_ptr &
