#!/usr/bin/bash

# Starts X automatically from the default login shell
if [[ ! `uname -s` == "Darwin" ]]; then
	[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx
fi

export PATH="$HOME/.cargo/bin:$PATH"
