source-all () {
	for f in $@; do
		. "$f"
	done
}

# Get grml if we do not have it installed already
if [[ ! -f ~/.zsh/grml.zsh ]]; then
	wget -O ~/.zsh/grml.zsh https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
fi

. ~/.zsh/grml.zsh

# Set theme
. ~/.zsh/themes/default.zsh
source-all `find ~/.zsh/plugins -type f`

if [[ ! -d ~/.zsh/completion ]]; then
	mkdir -p ~/.zsh/completion
	curl -L https://raw.githubusercontent.com/docker/compose/1.24.0/contrib/completion/zsh/_docker-compose > ~/.zsh/completion/_docker-compose
fi

fpath=(~/.zsh/completion ~/.zsh/conda-zsh-completion $fpath)
zstyle ':completion::complete:*' use-cache 1

if isdarwin; then
	fpath=(/usr/local/share/zsh-completions $fpath)
	fpath=(/usr/local/share/zsh/site-functions $fpath)
fi

[[ -n `compaudit` ]] && compaudit | xargs chmod g-w
rm -rf ~/.zcompdump; compinit

source-all \
	~/.zsh/env.zsh \
	~/.zsh/history.zsh \
	~/.zsh/functions.zsh \
	~/.zsh/prompt.zsh \
	~/.zsh/aliases.zsh \
	~/.zsh/options.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
